### ISSUE TITLE
`yarn setup-ios-jsc` and `yarn setup-ios-hermes` in rn-tester app failing

### ISSUE THREAD

**Issue by Marcoo09** [callstack/react-native-visionos#56]
### Description

After syncing with the remote, these commands start failing.

### Steps to reproduce

1. Pull latest version
2. yarn && cd packages/rn-tester && yarn clean-ios && yarn <any of the commands>

### React Native Version

0.74.0-nightly-20231205

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
OS: macOS 14.1
CPU: (10) arm64 Apple M2 Pro
Memory: 311.94 MB / 16.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 18.18.2
path: ~/.nvm/versions/node/v18.18.2/bin/node
Yarn:
version: 1.22.19
path: /opt/homebrew/bin/yarn
npm:
version: 9.8.1
path: ~/.nvm/versions/node/v18.18.2/bin/npm
Watchman:
version: 2023.10.23.00
path: /opt/homebrew/bin/watchman
Managers:
CocoaPods:
version: 1.14.3
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.0
- iOS 17.0
- macOS 14.0
- tvOS 17.0
- visionOS 1.0
- watchOS 10.0
Android SDK: Not Found
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.10121639
Xcode:
version: 15.1/15C5028h
path: /usr/bin/xcodebuild
Languages:
Java:
version: 17.0.8
path: /usr/bin/javac
Ruby:
version: 3.2.2
npmPackages:
"@react-native-community/cli": Not Found
react: Not Found
react-native: Not Found
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: false
newArchEnabled: false
iOS:
hermesEnabled: false
newArchEnabled: true
```

### Stacktrace or Logs

```text
[!] Invalid `Podfile` file: [!] /var/folders/k3/t5t6n81n1tl0qnpb6s7pb2xm0000gn/T/yarn--1702323120590-0.5598201253639083/node ./../react-native/scripts/generate-codegen-artifacts.js -p /
.../react-native-visionos/packages/rn-tester -o /.../react-native-visionos/packages/rn-tester -c /.../react-native-visionos/packages/rn-tester/node_modules



[Codegen] >>>>> Searching for codegen-enabled libraries in the project dependencies.
[Codegen] Found @callstack/react-native-visionos


[Codegen] >>>>> Searching for codegen-enabled libraries in the app
[Codegen] Found @react-native/tester


[Codegen] >>>>> Processing FBReactNativeSpec


[Codegen] >>>>> Processing rncore


[Codegen] >>>>> Processing AppSpecs


[Codegen] Done.
UnsupportedObjectPropertyValueTypeAnnotationParserError: Module NativeCxxModuleExample: Object property '[object Object]' cannot have type 'FunctionTypeAnnotation'.
    at throwIfPropertyValueTypeIsUnsupported (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/error-utils.js:185:9)
    at parseObjectProperty (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/parsers-commons.js:322:5)
 at /.../react-native-visionos/packages/react-native-codegen/lib/parsers/flow/modules/index.js:231:22
    at guard (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/utils.js:31:14)
    at /.../react-native-visionos/packages/react-native-codegen/lib/parsers/flow/modules/index.js:230:20
    at Array.map (<anonymous>)
    at translateTypeAnnotation (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/flow/modules/index.js:229:12)
    at /.../react-native-visionos/packages/react-native-codegen/lib/parsers/parsers-commons.js:358:11
    at guard (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/utils.js:31:14)
    at translateFunctionTypeAnnotation (/.../react-native-visionos/packages/react-native-codegen/lib/parsers/parsers-commons.js:352:25) {
  nodes: [
    {
      type: 'FunctionTypeAnnotation',
      loc: [Object],
      params: [Array],
      this: null,
      returnType: [Object],
      rest: null,
      typeParameters: null,
      range: [Array]
    }
  ]
}
```

### Reproducer

-

**Comment by okwasniewski** [comment]
Hey can you go to packages/react-native-codegen and run `yarn build`? 

Let me know if this fixes above issue

**Comment by Marcoo09** [comment]
Yes, it works now. Thank you!
